log:
  disable_sentry: true
  level: debug

db:
  url: db_url

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: "horizon"
  service_port: 80

cosmos:
  addr: "localhost:9090"


data:
  chains:
    - name: "Goerli"
      type: 0
      rpc: "wss://goerli.infura.io/ws/v3/..."
      icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png"
      chain_params:
        chain_id: "5"
        native_symbol: "ETH"
        explorer_url: "https://goerli.etherscan.io"
    - name: "Near"
      type: 2
      rpc: "https://rpc.testnet.near.org"
      icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/6535.png"
      chain_params:
        chain_id: "testnet"
        native_symbol: "NEAR"
        explorer_url: "https://explorer.testnet.near.org"
    - name: "Solana"
      type: 1
      rpc: "https://api.devnet.solana.com"
      icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png"
      chain_params:
        chain_id: "devnet"
        native_symbol: "SOL"
        explorer_url: "https://explorer.solana.com"

ipfs_gateway:
  credentials:
    - gateway_url: "https://ipfs..."
      project_id: ""
      project_secret: ""

chain_gateway:
  gateways:
    - name: "Solana"
      type: 1
      rpc: "https://..."
    - name: "Ethereum"
      type: 0
      rpc: "https://..."
