log:
  disable_sentry: true
  level: debug

db:
  url: postgres://horizon:horizon@localhost:5432/horizon?sslmode=disable

approvals_indexer:
  runner_name: "rarimocore-approvals-indexer"
  approvals_consumer:
    name: "rarimocore-approvals-consumer"
    queue: "rarimocore-approvals-q"

core:
  addr: "tcp://localhost:26657"

cosmos:
  addr: "localhost:9090"

redis:
  addr: "localhost:6379"
  db: 1
