log:
  disable_sentry: true
  level: debug

db:
  url: postgres://horizon:horizon@localhost:5432/horizon?sslmode=disable

block_ranges_producer:
  runner_name: "rarimocore-blockrange-producer"
  queue_name: "rarimocore-blocks-q"
  cursor_key: "rarimocore-blockrange-producer-cursor"
  block_range_limit: 100
  block_time: 5s

core:
  addr: "tcp://localhost:26657"

cosmos:
  addr: "localhost:9090"

redis:
  addr: "localhost:6379"
  db: 1
