log:
  disable_sentry: true
  level: debug

db:
  url: postgres://horizon:horizon@localhost:5432/horizon?sslmode=disable

confirmations_indexer:
  runner_name: "rarimocore-confirmations-indexer"
  confirmations_consumer:
    name: "rarimocore-confirmations-consumer"
    queue: "rarimocore-confirmations-q"

core:
  addr: "tcp://localhost:26657"

cosmos:
  addr: "localhost:9090"

redis:
  addr: "localhost:6379"
  db: 1
