log:
  disable_sentry: true
  level: debug

db:
  url: postgres://horizon:horizon@localhost:5432/horizon?sslmode=disable

block_ranges_producer:
  runner_name: "rarimocore-blockrange-producer"
  queue_name: "rarimocore-blocks-q"
  cursor_key: "rarimocore-blockrange-producer-cursor"
  block_range_limit: 100
  block_time: 5s

rarimocore_producer:
  runner_name: "rarimocore-events-producer"
  transfers_queue_name: "rarimocore-transfers-q"
  confirmations_queue_name: "rarimocore-confirmations-q"
  approvals_queue_name: "rarimocore-approvals-q"
  rejections_queue_name: "rarimocore-rejections-q"
  votes_queue_name: "rarimocore-votes-q"
  block_range_consumer:
    name: "rarimocore-blockrange-consumer"
    queue: "rarimocore-blocks-q"

transfers_indexer:
  runner_name: "rarimocore-transfers-indexer"
  transfers_consumer:
    name: "rarimocore-transfers-consumer"
    queue: "rarimocore-transfers-q"

confirmations_indexer:
  runner_name: "rarimocore-confirmations-indexer"
  confirmations_consumer:
    name: "rarimocore-confirmations-consumer"
    queue: "rarimocore-confirmations-q"

approvals_indexer:
  runner_name: "rarimocore-approvals-indexer"
  approvals_consumer:
    name: "rarimocore-approvals-consumer"
    queue: "rarimocore-approvals-q"

rejections_indexer:
  runner_name: "rarimocore-rejections-indexer"
  rejections_consumer:
    name: "rarimocore-rejections-consumer"
    queue: "rarimocore-rejections-q"

votes_indexer:
  runner_name: "rarimocore-votes-indexer"
  votes_consumer:
    name: "rarimocore-votes-consumer"
    queue: "rarimocore-votes-q"

core:
  addr: "tcp://localhost:26657"

cosmos:
  addr: "localhost:9090"

redis:
  addr: "localhost:6379"
  db: 1
