log:
  disable_sentry: true
  level: debug

db:
  url: postgres://horizon:horizon@localhost:5432/horizon?sslmode=disable

rejections_indexer:
  runner_name: "rarimocore-rejections-indexer"
  rejections_consumer:
    name: "rarimocore-rejections-consumer"
    queue: "rarimocore-rejections-q"

core:
  addr: "tcp://localhost:26657"

cosmos:
  addr: "localhost:9090"

redis:
  addr: "localhost:6379"
  db: 1
