log:
  disable_sentry: true
  level: debug

db:
  url: postgres://horizon:horizon@localhost:5432/horizon?sslmode=disable

transfers_indexer:
  runner_name: "rarimocore-transfers-indexer"
  transfers_consumer:
    name: "rarimocore-transfers-consumer"
    queue: "rarimocore-transfers-q"

core:
  addr: "tcp://localhost:26657"

cosmos:
  addr: "localhost:9090"

redis:
  addr: "localhost:6379"
  db: 1
