log:
  disable_sentry: true
  level: debug

db:
  url: postgres://horizon:horizon@localhost:5432/horizon?sslmode=disable

tokenmanager_producer:
  runner_name: "tokenmanager-events-producer"
  items_queue_name: "tokenmanager-items-q"
  collections_queue_name: "tokenmanager-collections-q"
  block_range_consumer:
    name: "tokenmanager-blockrange-consumer"
    queue: "tokenmanager-blocks-q"

core:
  addr: "tcp://localhost:26657"

cosmos:
  addr: "localhost:9090"

redis:
  addr: "localhost:6379"
  db: 1
